### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by bropines** [tumuyan/RealSR-NCNN-Android#1]
![Screenshot_2022-02-16-14-33-23-489_com tumuyan ncnn realsr](https://user-images.githubusercontent.com/57861007/154236415-96349ffd-841f-40fa-b283-177b50b8e5dd.jpg)
![Screenshot_2022-02-16-14-28-56-669_com tumuyan ncnn realsr](https://user-images.githubusercontent.com/57861007/154236445-0a92292a-5aca-4b3c-a5e7-d36985b017d2.jpg)

**Comment by tumuyan** [comment]
Please uninstall -> download https://github.com/tumuyan/RealSR-NCNN-Android/releases/download/1.4-debug/RealSR-NCNN-Android-GUI-armv8a-1.4.apk  -> reinstall -> open & run the same image -> upload screenshot

Thanks

**Comment by bropines** [comment]
I tested photos in resolution up to 500x500. They were working fine. In theory, the system cannot decode large-sized photos. 
![Screenshot_2022-02-16-17-04-15-388_com tumuyan ncnn realsr](https://user-images.githubusercontent.com/57861007/154261413-f2b14eed-4b70-4669-9a7f-fc8b0ad194dd.jpg)

**Comment by bropines** [comment]
Work:
![Screenshot_2022-02-16-17-41-38-494_com tumuyan ncnn realsr](https://user-images.githubusercontent.com/57861007/154268124-637963f2-65d1-429e-b457-6311636aca2c.jpg)
![313123123](https://user-images.githubusercontent.com/57861007/154268236-f5ca6276-6120-4b50-8d46-7df893455a0e.jpg)

No work: 
![WTuCRgBOffQ](https://user-images.githubusercontent.com/57861007/154268295-abb91bae-b087-4849-91f7-a485995c2cc9.jpg)
![Screenshot_2022-02-16-17-04-15-388_com tumuyan ncnn realsr](https://user-images.githubusercontent.com/57861007/154268391-2758f468-9ac4-4c91-aabb-5d5d65611571.jpg)


The current STB decoder cannot recognize some photos. I have attached what works and what doesn't

**Comment by tumuyan** [comment]
the file named as jpg, but actually it is a webp file.

Only png and jpg is support.

![Screenshot_2022-02-16-20-58-06-299_com.tumuyan.filemagic.debug.jpg](https://user-images.githubusercontent.com/3126801/154269648-f6601609-d05b-4b8e-8d64-a598cd489236.jpg)

**Comment by bropines** [comment]
Clear. In such ways, our local VK social network encodes uploaded photos.

**Comment by bropines** [comment]
And more. Nothing works on my device (Vulkan driver updated to the latest version) except real-esrgan 
![Screenshot_2022-02-16-17-58-00-589_com tumuyan ncnn realsr](https://user-images.githubusercontent.com/57861007/154279838-aa906cf5-166a-4b6f-a9f1-ea73d718ec44.jpg)
![Screenshot_2022-02-16-17-58-52-699_com tumuyan ncnn realsr](https://user-images.githubusercontent.com/57861007/154279850-58f3de85-94ae-45c0-a037-76df0fa37b1e.jpg)
![Screenshot_2022-02-16-17-57-37-575_com tumuyan ncnn realsr](https://user-images.githubusercontent.com/57861007/154279851-0b348cd9-e8e6-4f6b-add3-65d87356a5d0.jpg)

**Comment by tumuyan** [comment]
You could try these command (use -t parameter to set tile-size, small tile-size will be slow, default might be 200 ) and upload , refer https://github.com/nihui/realsr-ncnn-vulkan/issues/38  

```

./realsr-ncnn -i input.png -o output.png  -m models-DF2K_JPEG -t -100
./srmd-ncnn -i input.png -o output.png  -m models-srmd -s 2  -t 100
./realcugan-ncnn -i input.png -o output.png  -m models-se -s 2  -n -1 -t 100


```

**Comment by tumuyan** [comment]
now you can set the tile-size in setting activity

**Comment by bropines** [comment]
Yes, thanks. I think it's worth closing the issue, because the problem has been solved. As a suggestion, I can offer an image converter to the allowed format.
