### ISSUE TITLE
希望能够一次添加多个文件进行放大，同时显示预估剩余时间

### ISSUE THREAD

**Issue by JiHeWeiHuan** [tumuyan/RealSR-NCNN-Android#11]

**Comment by tumuyan** [comment]
out2input可以快速把输出结果作为输入，再次点击运行即可。运行剩余时间不计划做。
![IMG_20221116_190506](https://user-images.githubusercontent.com/3126801/202165133-d587f62c-3303-4976-ba8c-8dc1b72935b1.jpg)
