### ISSUE TITLE
✨incredible would be the possibility of an option that allows you to select multiple images✨

### ISSUE THREAD

**Issue by DavidSilvadeSa** [tumuyan/RealSR-NCNN-Android#12]
incredible would be the possibility of an option that allows you to select multiple images

and also the possibility for the image to be output with the same name as the input image

just serious AMAZING

**Comment by tumuyan** [comment]
it is too slow for mobile phone to process muliiple image.
So it's not really a practical feature. If you really need it, you can probably set up some shell commands
On high sdk level Android devices, there are some difficulties in getting the names of input files.

**Comment by DavidSilvadeSa** [comment]
I understood about the speed limitation of a cell phone

I believe adding the multiple image selection option will be wonderful

and make them come out with the same name as the input image will be divine

I think just put the images to be processed in queue order

a picture of each made it all automatic

**Comment by tumuyan** [comment]
now you could share multiple images from other apps (e.g., Gallery) to this app.  (>= 1.8)
