### ISSUE TITLE
如何编译GUI里调用的执行文件realsr-ncnn

### ISSUE THREAD

**Issue by xiazhenyz** [tumuyan/RealSR-NCNN-Android#18]
请问要在android测试自己的超分模型，现在GUI的proj里的realsr-ncnn、realcugan-ncnn这两个执行文件是怎么编译出来的？有基于nihui的代码修改吗？
谢谢~

**Comment by tumuyan** [comment]
编译方式其实有在说明里写,代码有改动但是只是细节上的处理:
https://github.com/tumuyan/RealSR-NCNN-Android/blob/master/README_CHS.md#%E5%A6%82%E4%BD%95%E7%BC%96%E8%AF%91-realsr-ncnn-android-cli

你是直接替换数据集还是修改了代码?
如果只是替换了训练集,是不需要重新编译的.
