### ISSUE TITLE
Not working when target SDK is 33 issue: "sh: <stdin>[2]: ./realsr-ncnn: can't execute: Permission denied"

### ISSUE THREAD

**Issue by syedusama5556** [tumuyan/RealSR-NCNN-Android#19]
Not working when target SDK is 33 issue: "sh: <stdin>[2]: ./realsr-ncnn: can't execute: Permission denied", 

when i make target SDK 33 , 32  it doesn't work but when i shift it back to 28 it works kindly fix it 

![image](https://user-images.githubusercontent.com/29094408/210178722-b70a9b94-b755-48aa-9a89-9863921e7351.png)

**Comment by tumuyan** [comment]
this project doesn't use jni, just run console.
so it could never support target SDK 33

**Comment by syedusama5556** [comment]
how can we make it support it using jni can you explain a little

**Comment by tumuyan** [comment]
Actually, I use this solution just because I don't have the ability to develop a jni projects.

**Comment by RobbWatershed** [comment]
Adding the corresponding API changelog for future reference : https://developer.android.com/about/versions/10/behavior-changes-10#execute-permission

**Comment by RobbWatershed** [comment]
The fix is writing the JNI bridge 😋 

I'm currently considering whether to invest time on this or not. You might hear about me again soon 😉

**Comment by RobbWatershed** [comment]
There's another structural issue here : this repo has actually two kinds of products
- The console CLI : command-line programs written in CPP and directly linked to NCNN
- The Android GUI : frontend that launches CLIs and displays the results

Linking the GUI to NCNN directly via JNI would require to do important changes to the structure of that repo, and I'm not certain those changes would go in the direction the maintainer wants.

As I'm only interested in the GUI, I'll probably end up working on my own fork and getting rid of CLIs.

**Comment by RobbWatershed** [comment]
@syedusama5556 I eventually made my own integration as an Android native library using RealCUGAN exclusively : https://github.com/avluis/Hentoid/tree/dev/app/ai-upscale

It works like a charm on my app, which targets API33

**Comment by tumuyan** [comment]
> @syedusama5556 I eventually made my own integration as an Android native library using RealCUGAN exclusively : https://github.com/avluis/Hentoid/tree/dev/app/ai-upscale
> 
> It works like a charm on my app, which targets API33

nice work , but it's more flexible to use a cli program for myself.
I find your repo is a manga app, does the process speed match read speed? Maybe anime4k or bicubicd+ + is better.

**Comment by RobbWatershed** [comment]
> nice work , but it's more flexible to use a cli program for myself.

Sure, no problem. I was simply answering syedusama's question about how to call NCNN from an API33 Android app.

> I find your repo is a manga app, does the process speed match read speed? Maybe anime4k or bicubicd+ + is better.

NCNN is not use for real-time reading, but in a feature called "Transform" used to upscale all pictures of a given book.

That being said :

- **anime4k** : I've considered it, but the only thing I found so far were MPV-specific GLSL shaders, not "standalone" GLSL shaders usable from inside an OpenGL app (see https://github.com/bloc97/Anime4K/issues/120)

- **bicubicd++" : What is that ? Do you have any link to provide ?

**Comment by tumuyan** [comment]
@RobbWatershed 
This repo has build Anime4k for Android, not the latest version
https://github.com/TianZerL/Anime4KCPP

bicbic++ only has python repo.
https://github.com/aselsan-research-imaging-team/bicubic-plusplus
