### ISSUE TITLE
is it possible to make GFPGAN work on android?

### ISSUE THREAD

**Issue by GeorvityLabs** [tumuyan/RealSR-NCNN-Android#2]
Similar to how you setup SR GAN , do you think it's possible to make GFPGAN work on images via android.
would be great if you could try to make a similar project.
ncnn gfpgan + android.

**Comment by tumuyan** [comment]
realse was setuped by nihui, from https://github.com/nihui/realsr-ncnn-vulkan
I just build it in android.
Cause of there is no gfpgan-ncnn-vulkan project, it's hard to make gfpgan-android

**Comment by tumuyan** [comment]
I find a ncnn project, but the model is too large to work on android

https://github.com/FeiGeChuanShu/GFPGAN-ncnn

**Comment by GeorvityLabs** [comment]
also Real CUGAN GUI possible on android?

**Comment by tumuyan** [comment]
Real-CUGAN has been added last week

**Comment by ProfessorSparrs** [comment]
this app is AMAZING  why is this not on fdroid? One complaint tho. im not a dev but Im tech savvy but none of my devices seems to use the GPU for upscaling anything. isnt Vulkan used for this? I get good results with other upscaling apps with my Adreno GPU used on my Oneplus 5t and my Xiaomi Pad 5.  But your app is soo customizable.. CPU upscaling I feel is much slower than using the GPU chipset
