### ISSUE TITLE
How to batch running the images?

### ISSUE THREAD

**Issue by vannessqn** [tumuyan/RealSR-NCNN-Android#22]
I want to upscale manga chapter from mangaplus because its low quality it would be great if I can just put in the folder and it will upscale all the chapter thank you!

**Comment by tumuyan** [comment]
now you could share multiple images from other apps (e.g., Gallery) to this app.  (>= 1.8)

**Comment by vannessqn** [comment]
Yayy very nice I will try it tonight ty!!
