### ISSUE TITLE
安卓移动设备上部分模型发生 vkQueueSubmit failed -4 问题

### ISSUE THREAD

**Issue by JsGarcia5** [tumuyan/RealSR-NCNN-Android#26]
Redmi Note 12 Turbo
Android 13 - MIUI 14
Qualcomm Snapdragon 7+ Gen 2 (SM7475-AB)
12GB RAM
GPU: Adreno 725
CPU: 1x 2.91 GHz Cortex-A710, 3x 2.49 GHz Cortex-A710, 4x 1.8 GHz Cortex-A510

默认软件设置下，在 real-esrgan-anime-x4, real-esrgan-x4, srmd-x4(3,2) 时，皆表示 vkQueueSubmit failed -4：

[0 Adreno (TM) 725] queueC=0[3] queueG=0[3]
queueT=0[3]
[0 Adreno (TM) 725] bugsbn1=1 bugbilz=0
bugcopc=0 bugihfa=0
[0 Adreno (TM) 725] fp16-p/s/a=1/1/1 int8-p/s/a=1/1/1
[0 Adreno (TM) 725] subgroup=64 basic=1 vote=1 ballot=1 shuffle=1

busy...

stbi_load_from_memory get channel 3
input&output w/h/c 1280/1920/1 5120/7680/1

0.00%
vkQueueSubmit failed -4
1.43%
vkQueueSubmit failed -4
2.86%
...
98.57%
vkQueueSubmit failed -4
save result...
save result use time: 17.008

产出白色图片。

默认软件设置下，在 real-esrganv3(2)-anime-x4(3,2), 所有的 real-cugan 模型时，皆顺利处理图片。
CPU模式下，在上述模型中，只有 real-cugan 系列模型正常，其他模型皆产出撕裂图片（见附件）。

________________________________
本人另有一部 Realme Q2
Android 11 - REALME UI 2
SoC:MediaTek Dimensity 800U
CPU: 2x 2.4 GHz ARM Cortex-A76, 6x 2.0 GHz ARM Cortex-A55, Cores: 8
GPU: ARM Mali-G57 MC3, Cores:3
4GB RAM
默认软件设置下所以模型运行成功。

求助内容：
不清楚在更高性能的设备上为何会出现问题。
若需要我会提供更多信息。
反馈内容里可能有表述不清晰的地方，请见谅。

**Comment by JsGarcia5** [comment]
附件

**Comment by JsGarcia5** [comment]
1

**Comment by tumuyan** [comment]
参考常见错误：https://note.youdao.com/s/3xv6h5iv
你可以试试输入较小图片是否正常
你也可以试试这个测试版 https://github.com/tumuyan/RealSR-NCNN-Android/releases/download/pre-release-202305/RealSR-NCNN-Android-GUI-armv8a-1.8.3.apk

类似的反馈我有收到许多，甚至我的一台旧手机也有同样的错误。目前的经验是高通芯片的兼容性要比其他（比如MTK）更差一些，和性能似乎关系不大。

**Comment by JsGarcia5** [comment]
参考文档，在测试版调整Tile Size之后运行成功了。
谢谢！
