### ISSUE TITLE
Gif / Video support.

### ISSUE THREAD

**Issue by instaelse** [tumuyan/RealSR-NCNN-Android#27]
Just like in issue #15. Have the app break the gifs / videos into frames, run the model and then combine the frames back. Could be useful. Its a little tiring doing this manually.

**Comment by tumuyan** [comment]
If your device takes 5 seconds to for one picture, then it takes 5*25*10/60=20min to zoom in on a 10 second video file with 25 frames per second. Actually, the time will more than 20 min. 
You should use a PC or server with a powerful GPU to do such tasks.
