### ISSUE TITLE
文档教程没看明白，工程导入后失败，请问要怎样才能在AS上成功运行那个GUI程序？

### ISSUE THREAD

**Issue by JackyWu15** [tumuyan/RealSR-NCNN-Android#3]

**Comment by JackyWu15** [comment]
导入工程后提示Could not find method dependencyResolutionManagement()

**Comment by tumuyan** [comment]
编译gui没有复杂操作，下载assets以及工程，直接用as打开gui目录即可，没有复杂操作。  
你可以百度一下 Could not find method dependencyResolutionManagement，应该是gradle和as版本的问题。

**Comment by JackyWu15** [comment]
> 编译gui没有复杂操作，下载assets以及工程，直接用as打开gui目录即可，没有复杂操作。 你可以百度一下 Could not find method dependencyResolutionManagement，应该是gradle和as版本的问题。

运行起来了，要升级AS 到Bumblebee以上版本
