### ISSUE TITLE
多选图片

### ISSUE THREAD

**Issue by User-from-BiliBili** [tumuyan/RealSR-NCNN-Android#30]
由于我想弄大的图片非常多，希望作者能添加多选图片，虽然设置有保存多个图片名字，但是我却不理解为什么不能多选图片

**Comment by tumuyan** [comment]
从每个相册或者文件管理器多选图片，分享到RealSr

**Comment by User-from-BiliBili** [comment]
> 从每个相册或者文件管理器多选图片，分享到RealSr

谢谢
