### ISSUE TITLE
多个图片高清导出提示没有待导出的文件，更换其他手机后依旧如此

### ISSUE THREAD

**Issue by lanxia00** [tumuyan/RealSR-NCNN-Android#39]
单个图片可以很好的正常导出高清图片，但数量一变成2或者更多时，显示保存成功，但是导出错误，提示没有待导出的文件，该怎么解决这个问题呢？我在爱发电上也询问了，以下是运行显示内容
search model:models-Real-ESRGANv3-anime/
x2.bin
[O Mali-G715-Immortalis MC11] queueC=0[2]
queueG=0[2] queueT=0[2]
[O Mali-G715-lmmortalis MC11] bugsbn1=0
bugbilz=0 bugcopc=0 bugihfa=0
[O Mali-G715-Immortalis MC11] fp16-p/s/
a=1/1/1 int8-p/s/a=1/1/1
[O Mali-G715-Immortalis MC11] subgroup=16
basic/vote/ballot/shuffle=1/1/1/1
[O Mali-G715-Immortalis MC11]
fp16-matrix-16_8_8/16_8_16/16_16_16=0/0/0
channel=3, stbi_load_from_memory
scale=2, w/h/c 654/1166/1 -> 1308/2332/1
channel=3, stbi_load_from_memory
scale=2, w/h/c 440/247/1 -> 880/494/1
save result use time: 0.238save result use time: 1.473Total use time: 6.258
finish, use 6.366 second
Real-ESRGANv3-anime

**Comment by tumuyan** [comment]
多选图片并处理成功后,不显示处理结果,图片自动导出并弹出toast消息,无需手动点击导出.


![IMG_20231017_123246](https://github.com/tumuyan/RealSR-NCNN-Android/assets/3126801/09c604ef-8a49-4b65-901d-fc82c10c1f78)

**Comment by tumuyan** [comment]
请再检查下输出的目录中是否有处理后的结果,
考虑到这个机制可能造成困扰,我后边会在使用多选图片时,把导出按钮隐藏掉.

**Comment by lanxia00** [comment]
> 请再检查下输出的目录中是否有处理后的结果, 考虑到这个机制可能造成困扰,我后边会在使用多选图片时,把导出按钮隐藏掉.

你好，我发现问题了，图片是保存到本地了没错，但是直接从手机相册里查看里面并没有显示，不过从文件管理里面可以找到高清过的图片

**Comment by tumuyan** [comment]
https://github.com/tumuyan/RealSR-NCNN-Android/releases/download/1.9.1/RealSR-NCNN-Android-GUI-armv8a-1.9.1-2023-10-23.apk

更新一下，应该已经解决了这个问题
