### ISSUE TITLE
Error: sh: [1]: cd: /data/user/0/com.tumuyan.ncnn.realsr/ cache/realsr: No such file or directory

### ISSUE THREAD

**Issue by md-rifatkhan** [tumuyan/RealSR-NCNN-Android#42]
I wanna trying to upscale image with gui, i've pasted all realsr files to assets folder.  Got this error when running

sh: [1]: cd: /data/user/0/com.tumuyan.ncnn.realsr/ cache/realsr: No such file or directory
chmod: *ncnn: No such file or directory
sh: [2]: ./realsr-ncnn: inaccessible or not found
finish, use 0.02 second, Real-ESRGAN

**Comment by tumuyan** [comment]
The App could extract all these files, try to install the latest version and clear all data in app info, open the app and wait 20 seconds, then select a image.
