### ISSUE TITLE
Black Image result on termux cli

### ISSUE THREAD

**Issue by rkhyper** [tumuyan/RealSR-NCNN-Android#43]
./realsr-ncnn -i input.jpg -o output.jpg -m models-Real-ESRGAN -s 3 

I used: curl https://huggingface.co/spaces/tumuyan/RealSR/raw/main/install_realsr_android.sh | bash

Result image is black, log: input&output w/h/c 1000/662/1 4000/2648/1
0.00%
vkQueueSubmit failed -4
5.00%
vkQueueSubmit failed -4
10.00%
vkQueueSubmit failed -4
15.00%
vkQueueSubmit failed -4
20.00%
vkQueueSubmit failed -4
vkQueueSubmit failed -4
vkQueueSubmit failed -4
25.00%
vkQueueSubmit failed -4
30.00%
vkQueueSubmit failed -4
35.00%
vkQueueSubmit failed -4
40.00%
vkQueueSubmit failed -4
45.00%
vkQueueSubmit failed -4
vkQueueSubmit failed -4
vkQueueSubmit failed -4
50.00%
vkQueueSubmit failed -4
55.00%
vkQueueSubmit failed -4
60.00%
vkQueueSubmit failed -4
65.00%
vkQueueSubmit failed -4
70.00%
vkQueueSubmit failed -4
vkQueueSubmit failed -4
vkQueueSubmit failed -4
75.00%
vkQueueSubmit failed -4
80.00%
vkQueueSubmit failed -4
85.00%
vkQueueSubmit failed -4
90.00%
vkQueueSubmit failed -4
95.00%
vkQueueSubmit failed -4
save result...
save result use time: 0.792
Total use time: 6.589

**Comment by tumuyan** [comment]
#23
