### ISSUE TITLE
How to convert real esrgan?

### ISSUE THREAD

**Issue by einsqing** [tumuyan/RealSR-NCNN-Android#45]
我使用onnx2ncnn，提示find_blob_index_by_name失败
![微信图片_20231031112340](https://github.com/tumuyan/RealSR-NCNN-Android/assets/7685948/500d1c54-1b3a-4d25-a438-b08b17d00803)

**Comment by tumuyan** [comment]
见ReadMe

https://github.com/tumuyan/RealSR-NCNN-Android/blob/master/README_CHS.md#%E4%B8%BA-realsr-ncnn-android-gui-%E5%A2%9E%E5%8A%A0%E6%9B%B4%E5%A4%9A%E6%A8%A1%E5%9E%8B

**Comment by tumuyan** [comment]
不对 你需要看real-esrgan的readme  https://github.com/xinntao/Real-ESRGAN/blob/master/docs/ncnn_conversion.md

**Comment by einsqing** [comment]
> 不对 你需要看real-esrgan的readme https://github.com/xinntao/Real-ESRGAN/blob/master/docs/ncnn_conversion.md

其中提到的ncnn工具是https://github.com/Tencent/ncnn么？我测试了不行，Modify the blob name in realesrgan-x4.param: data and output这句话要如何操作？

**Comment by tumuyan** [comment]
转换结果包含bin和param两个文件，使用文本编辑器打开后者，可以看到ncnn网络结构。文件头部几行需要把输入参数名替换为data，文件尾部的输出需要改为output，可以参考正常可用的模型进行确认
