### ISSUE TITLE
骁龙7+，使用real-esrgan模型在手机上一帧图3.2s

### ISSUE THREAD

**Issue by einsqing** [tumuyan/RealSR-NCNN-Android#46]
骁龙7+，使用real-esrgan模型在手机上一帧图3.2s，fp32和fp16都测试了，速度差不多，都得3s，请问有什么加速方案么？

**Comment by tumuyan** [comment]
内置real-esrgan模型本身已经是fp16并且大佬深度优化过了，所以速度没有差别。想再加速不是简单的事情了。
