### ISSUE TITLE
安装之后模型不能被加载处理图像问题，没有处理结果

### ISSUE THREAD

**Issue by love112358** [tumuyan/RealSR-NCNN-Android#47]
大神们请教几个问题 @tumuyan 
这里是手机处理结果界面
![image](https://github.com/tumuyan/RealSR-NCNN-Android/assets/33959491/5a58402a-2c05-4068-934c-6d87ceb5fc11)
这里是手机app的一些设置 好像没有这样的路径
![image](https://github.com/tumuyan/RealSR-NCNN-Android/assets/33959491/b6c04781-7044-48cd-b090-a4a587190408)
![image](https://github.com/tumuyan/RealSR-NCNN-Android/assets/33959491/cbf2fc72-64c9-419c-83dd-83cbb782060a)

是我哪里操作有问题吗
![微信截图_20231222111217](https://github.com/tumuyan/RealSR-NCNN-Android/assets/33959491/79d77e9f-f044-465f-b73b-7f48d46472fe)
![微信截图_20231222111344](https://github.com/tumuyan/RealSR-NCNN-Android/assets/33959491/762478ba-689c-41f8-96a0-96cfd8c83016)
![微信截图_20231222111415](https://github.com/tumuyan/RealSR-NCNN-Android/assets/33959491/5595df5f-07f8-48a6-b857-c47d2781fc64)

**Comment by love112358** [comment]
已经解决了 谢谢

**Comment by ZMxyxyxy** [comment]
您好，我也遇到了题主的问题，我下载好其他模型后，按照步骤填入命令，但运行后，处理后的图片不存在，也不能导出，请问应该怎么解决呢？
