### ISSUE TITLE
请教一个问题gui和cli 之间是什么关系呢 

### ISSUE THREAD

**Issue by love112358** [tumuyan/RealSR-NCNN-Android#48]
这里的RealSR-NCNN-Android-GUI  RealSR-NCNN-Android-CLI  这里的gui和cli是什么关系呢 我我是在RealSR-NCNN-Android工程下编译呢 还是分别在RealSR-NCNN-Android-GUI 和RealSR-NCNN-Android-CLI   下编译 或者 只编译RealSR-NCNN-Android-GUI  这个工程 就可以了呢
![image](https://github.com/tumuyan/RealSR-NCNN-Android/assets/33959491/0162db21-d36c-448d-87c4-34b1ac15d334)

**Comment by tumuyan** [comment]
cli编译的结果可以在虚拟终端中直接使用，gui编译的结果为apk。
打包apk时需要有cli编译结果以及模型，可以自己编译也可以下载我的编译结果。 

编译是分开编译各个项目的。
