### ISSUE TITLE
编译resize-cli遇到git 和cmake问题

### ISSUE THREAD

**Issue by love112358** [tumuyan/RealSR-NCNN-Android#49]
这里是git的问题![image](https://github.com/tumuyan/RealSR-NCNN-Android/assets/33959491/c2177746-4811-400d-a23d-58ef36af63a9)

下面是cmake的问题
Execution failed for task ':app:configureCMakeRelWithDebInfo[arm64-v8a]'.
> [CXX1405] error when building with cmake using E:\work_project\RealSR-NCNN-Android\Resize-CLI\app\src\main\jni\CMakeLists.txt: Build command failed.
  Error while executing process D:\worksoft\android_sdk\cmake\3.18.1\bin\cmake.exe with arguments {-HE:\work_project\RealSR-NCNN-Android\Resize-CLI\app\src\main\jni -DCMAKE_SYSTEM_NAME=Android -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DCMAKE_SYSTEM_VERSION=24 -DANDROID_PLATFORM=android-24 -DANDROID_ABI=arm64-v8a -DCMAKE_ANDROID_ARCH_ABI=arm64-v8a -DANDROID_NDK=D:\worksoft\android_sdk\ndk\22.1.7171670 -DCMAKE_ANDROID_NDK=D:\worksoft\android_sdk\ndk\22.1.7171670 -DCMAKE_TOOLCHAIN_FILE=D:\worksoft\android_sdk\ndk\22.1.7171670\build\cmake\android.toolchain.cmake -DCMAKE_MAKE_PROGRAM=D:\worksoft\android_sdk\cmake\3.18.1\bin\ninja.exe -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=E:\work_project\RealSR-NCNN-Android\Resize-CLI\app\build\intermediates\cxx\RelWithDebInfo\3s5y3h3d\obj\arm64-v8a -DCMAKE_RUNTIME_OUTPUT_DIRECTORY=E:\work_project\RealSR-NCNN-Android\Resize-CLI\app\build\intermediates\cxx\RelWithDebInfo\3s5y3h3d\obj\arm64-v8a -DCMAKE_BUILD_TYPE=RelWithDebInfo -BE:\work_project\RealSR-NCNN-Android\Resize-CLI\app\.cxx\RelWithDebInfo\3s5y3h3d\arm64-v8a -GNinja}
  -- Detecting C compiler ABI info
  -- Detecting C compiler ABI info - done
  -- Check for working C compiler: D:/worksoft/android_sdk/ndk/22.1.7171670/toolchains/llvm/prebuilt/windows-x86_64/bin/clang.exe - skipped
  -- Detecting C compile features
  -- Detecting C compile features - done
  -- Detecting CXX compiler ABI info
  -- Detecting CXX compiler ABI info - done
  -- Check for working CXX compiler: D:/worksoft/android_sdk/ndk/22.1.7171670/toolchains/llvm/prebuilt/windows-x86_64/bin/clang++.exe - skipped
  -- Detecting CXX compile features
  -- Detecting CXX compile features - done
  -- Configuring incomplete, errors occurred!
  See also "E:/work_project/RealSR-NCNN-Android/Resize-CLI/app/.cxx/RelWithDebInfo/3s5y3h3d/arm64-v8a/CMakeFiles/CMakeOutput.log".

**Comment by tumuyan** [comment]
https://github.com/tumuyan/RealSR-NCNN-Android/blob/master/README_CHS.md#%E5%A6%82%E4%BD%95%E7%BC%96%E8%AF%91-realsr-ncnn-android-cli

**Comment by love112358** [comment]
已经解决了 谢谢
