### ISSUE TITLE
关于下载更多模型的地址打不开问题

### ISSUE THREAD

**Issue by love112358** [tumuyan/RealSR-NCNN-Android#50]
你好呀 我想根据你提供的地址https://huggingface.co/tumuyan/realsr 下载更多模型，但是发现这个地址找不到404 能提供新的地址吗
@tumuyan 
![image](https://github.com/tumuyan/RealSR-NCNN-Android/assets/33959491/a9780449-45ea-4a40-abf0-1ea94bd2ee0f)

**Comment by tumuyan** [comment]
账户可能被ban了，我也打不开了；；

**Comment by love112358** [comment]
@tumuyan 你们提供一下新的地址，并上传新的模型吗关于上面地址打不开的问题，或者您告诉我都有哪些模型我自己去找 自己处理

**Comment by tumuyan** [comment]
由于huggingface没有恢复我的账户，昨天已经在github上传。
https://github.com/tumuyan/realsr-models
