### ISSUE TITLE
酷安链接打不开

### ISSUE THREAD

**Issue by Final0i00000000a7** [tumuyan/RealSR-NCNN-Android#51]

**Comment by Final0i00000000a7** [comment]
![Screenshot_2024-01-27-13-49-22-624_com lemurbrowser exts](https://github.com/tumuyan/RealSR-NCNN-Android/assets/140218829/9e54d167-3f4e-4fd7-ab74-8b82fe8bf06f)

**Comment by tumuyan** [comment]
酷安已经批量下架未备案应用。
