### ISSUE TITLE
关于模型加载和 推理过程的c++代码转换成库文件的问题

### ISSUE THREAD

**Issue by love112358** [tumuyan/RealSR-NCNN-Android#55]
你好我在写通过c++代码 写加载模型和模型推理的整个类容，但是通过编译成库文件时 成功了 但是在我自己的项目中编译成apk后 执行相应的操作却是 失败的  你可以上穿一下你这部分的代码吗 我想作为参考 然后编译我自己的模型加载 和模型推理的函数接口 然后在自己编译成。so静态库文件。望回复 @tumuyan  感谢

**Comment by tumuyan** [comment]
全部代码已经都在仓库中。
这个项目使用ncnn推理，直接把模型路径字符串传给ncnn就已经完事了。
并且编译结果是一系列命令行程序，并没有设计接口供jni调用。

**Comment by love112358** [comment]
好的 谢谢
