### ISSUE TITLE
为什么编译出来的apk和releases的不一样

### ISSUE THREAD

**Issue by lishangwl** [tumuyan/RealSR-NCNN-Android#58]
编译出来的没有模型

**Comment by tumuyan** [comment]
可以从release apk中提取assets并放到project中。见说明   https://github.com/tumuyan/RealSR-NCNN-Android/blob/master/README_CHS.md#%E5%A6%82%E4%BD%95%E7%BC%96%E8%AF%91-realsr-ncnn-android-gui

**Comment by lishangwl** [comment]
好的，关闭吧，已经知道了。

**Comment by lishangwl** [comment]
感谢回复
