### ISSUE TITLE
errorResult: sh: <stdin>[2]: ./srmd-ncnn: No such file or directory

### ISSUE THREAD

**Issue by JackyWu15** [tumuyan/RealSR-NCNN-Android#6]
请问GUI项目在手机上运行没问题，但在电视上出现了errorResult: sh: <stdin>[2]: ./srmd-ncnn: No such file or directory错误，有可能是什么原因呢？

**Comment by tumuyan** [comment]
重启电视机试试?如果不行,
在文本框内输入 ls -l 回车并截屏
输入pwd 回车并截屏

**Comment by JackyWu15** [comment]
换了个机器报errorResult: sh: <stdin>[2]: ./realcugan-ncnn: not executable: 64-bit ELF file，可能是同样问题，64位的不能用，能提供32位的ELF 文件吗

**Comment by tumuyan** [comment]
早些时候有编译32位elf文件,可以翻一下release.
用命令拷贝文件到data目录的包名下边的cache/realsa就可以用了.
我觉得没有64位支持的机器应该比较旧了,恐怕gpu不怎么样,最终结果就是完全跑不动.

**Comment by JackyWu15** [comment]
可以跑起来，效果很棒，不过我们想把处理过程用在电视lancher上，公司又对在lancher上使用getRuntime这种方式做了限制，如果想通过JNI的方式调用，要怎么做呢？

**Comment by tumuyan** [comment]
这个项目本质就是在Android平台重新编译nihui大佬的几个cli项目，并不方便改为jni调用。

**Comment by ArchieMeng** [comment]
> 可以跑起来，效果很棒，不过我们想把处理过程用在电视lancher上，公司又对在lancher上使用getRuntime这种方式做了限制，如果想通过JNI的方式调用，要怎么做呢？

不知道你有没有解决问题。不过我刚刚把我那个应用怎么做JNI的给公开了。https://github.com/ArchieMeng/ncnn-android-waifu2x-demo
你改一改就可以用其他的项目的啦。

**Comment by tumuyan** [comment]
> > 可以跑起来，效果很棒，不过我们想把处理过程用在电视lancher上，公司又对在lancher上使用getRuntime这种方式做了限制，如果想通过JNI的方式调用，要怎么做呢？
> 
> 不知道你有没有解决问题。不过我刚刚把我那个应用怎么做JNI的给公开了。https://github.com/ArchieMeng/ncnn-android-waifu2x-demo 你改一改就可以用其他的项目的啦。

感谢分享  但是我发现cli套壳某种程度也有好处：比如编译pc版在vs里debug，测试完直接给Android用，而不需要修改代码。再比如直接丢其他cli程序比如magick去用。如果说缺点，恐怕也只有分块处理的时候无法预览，以及系统本身有限制的问题了。
