### ISSUE TITLE
 请教：RealSR 模块编译，是否需要依赖 OpenCV

### ISSUE THREAD

**Issue by aerzha** [tumuyan/RealSR-NCNN-Android#60]
您好，我打算搞下android 上 jni 调用，先拿 RealSR 试一下

根据文档 CLI 编译说明，导入了 ncnn和libwebp，但编译不通过，注释掉 CMakeLists.txt 相关依赖 OpenCV 代码，编译通过

但文档上说 **下载opencv-android-sdk(供Anime4k使用)**， 所以比较疑惑 RealSR 模块是否也需要依赖 OpenCV

**Comment by tumuyan** [comment]
原先只有anime4k需要opencv，
后来发现opencv保存图片具有速度上的优势，所以全部改用opencv保存结果了
