### ISSUE TITLE
Additional models

### ISSUE THREAD

**Issue by vmobilis** [tumuyan/RealSR-NCNN-Android#61]
@tumuyan, hello and thank you for the program, it works great!

Could you please add these 2 models to your model repository?
https://openmodeldb.info/models/8x-TGHQFace (faces x8)
https://openmodeldb.info/models/4x-LSDIRplusN (generic x4)

Or at least faces. If it's not too difficult, I failed to make it myself. :)
Thanks in advance!

**Comment by tumuyan** [comment]
I have add models-ESRGAN-TGHQFace to the models repo.

You could get LSDIRplus ncnn models from the origin repo (make a dir, download and rename the models as x4.bin & x4.param )
 https://github.com/Phhofm/models/tree/main/4xLSDIRplus

**Comment by vmobilis** [comment]
@tumuyan, your model works, 非常感谢你！ 🙂

I tried to use NCNN models from Phhofm repository, but they crash with message:

<code>find_blob_index_by_name data failed
Try
&nbsp;&nbsp;ex.input("input", in0);
Segmentation fault
</code>

(The model was renamed to "models-ESRGAN-4x_LSDIRplusN_fp32/x4.param").

Also, I tried to run ONNX versions of models through "onnxsim" (pip package) and then convert result with "onnx2ncnn" (from NCNN tools).
Same crash, so maybe those LSDIRplus models are not compatible.

Anyway, thank you very much!

**Comment by tumuyan** [comment]
emmm  you should replace ‘input’ to ‘data’
i have modify the param file.

[4xLSDIRplusN_fp32.param.zip](https://github.com/tumuyan/RealSR-NCNN-Android/files/15125602/4xLSDIRplusN_fp32.param.zip)
