### ISSUE TITLE
下载下来的代码用android studio运行之后不能载入图片，apk下载下来却是正常的

### ISSUE THREAD

**Issue by luomulo** [tumuyan/RealSR-NCNN-Android#66]
![Snipaste_2024-06-12_16-50-37](https://github.com/tumuyan/RealSR-NCNN-Android/assets/96601524/7419e54e-ab16-445c-b25b-e750e26b2f2d)

**Comment by tumuyan** [comment]
应该是缺assets，看下readme把assets下载解压正确放入工程中。

**Comment by luomulo** [comment]
> 应该是缺assets，看下readme把assets下载解压正确放入工程中。

已解决，谢谢
