### ISSUE TITLE
大佬，提个问题，这个有办法原生集成吗？

### ISSUE THREAD

**Issue by zippozeng** [tumuyan/RealSR-NCNN-Android#7]
不想使用不适用commond的方式来实行的话，可以通过JNI来调python吗?

**Comment by tumuyan** [comment]
不可以.command的效率并不比jni调用so文件效率低.
事实上Python环境要求很复杂, 甚至在Android里跑termux, termux直接安装Python环境,都不能正常安装这些算法.
