### ISSUE TITLE
Custom resolution option

### ISSUE THREAD

**Issue by DavidAriyan** [tumuyan/RealSR-NCNN-Android#71]
This app is great but I think it's need an option to set resolution to whatever we want. Other similar app have 4x output to 2160p from a 1080p. And the results is a 4k image with 8k quality. I actually only prefer the Esgran v3 general to upscale image that's not 2d illustration but the results is in 8k from 1080p which is so big. Majority of them has at least 30mb per image. Waste of space. I can use that other app to upscale natively from device buy it's makes my phone so hot looks like it's using cpu instead of GPU. 
I hope RealSR will have this basic feature.

**Comment by tumuyan** [comment]
you could add custom command `./realsr-ncnn -i input.png -o temp.png  -m models-Real-ESRGAN ; ./magick temp.png -resize  "2560x2560>" output.png `  
![Screenshot_2024-11-23-19-08-06-405_com tumuyan nc](https://github.com/user-attachments/assets/642c5c6b-43ff-4478-a1b2-9385eced4fc0)


or use the function `output -> input` and `Magick 25%` to resize the result.

![Screenshot_2024-11-23-18-41-27-775_com tumuyan nc](https://github.com/user-attachments/assets/579bac59-4032-40ad-9d19-7408b4e2ffc7)

**Comment by DavidAriyan** [comment]
Yeah the output -> input and Magick 50% works for me. But the command
doesn't work, it's fail. I don't know why..
But I really appreciate your guide. At least I can use it now even with two
step process.
Thank you very much. The app really useful.

Pada Sab, 23 Nov 2024 18.13, tumuyan ***@***.***> menulis:

**Comment by DavidAriyan** [comment]
I found that the realsr general v3 results is bad.  What's the best models
to upscale digital photo image like movie poster? I'm new into this so
need a recommendation. Thanks for helping me. I'll close the issue because
there's already solution.


Pada Sab, 23 Nov 2024 18.37, David Ariyan ***@***.***>
menulis:

**Comment by DavidAriyan** [comment]
I need a recommendation best models for movie posters upscaling or photos. Esgranx4 is really slow I hope there's other best models I'm new into this

**Comment by DavidAriyan** [comment]
I need a models that didn't screwed up the grain and didn't make the person looks like anime

**Comment by RobbWatershed** [comment]
@DavidAriyan you gotta use the app to do your own benchmark and choose the best compromise between quality and performance.

Claiming "I want a model that does X" on a GitHub issue won't get you anywhere.

**Comment by tumuyan** [comment]
> Esgranx4 is really slow I hope there's other best models I'm new into this

Most models couldn't faster than REAL-ESRGAN.



> I need a recommendation best models for movie posters upscaling or photos.

I recommend you try the Nomos8kSC model. The result has less sharp.

**Comment by DavidAriyan** [comment]
Ok thanks. Have a great day

Pada Sab, 23 Nov 2024 20.17, tumuyan ***@***.***> menulis:
