### ISSUE TITLE
suggestion to add some more new models.

### ISSUE THREAD

**Issue by ARTUROSING** [tumuyan/RealSR-NCNN-Android#9]
Models A-ESRGAN https://github.com/Zi-hao-Wei/A-ESRGAN , Real EDRGAN + LDL https://github.com/csjliang/LDL. Thank you.

**Comment by ARTUROSING** [comment]
I will be very grateful to you.

**Comment by tumuyan** [comment]
In fact I have no experience of deploying Python projects to Android devices, all I have done is compile C projects for Android and create a UI for them. 

```

ncnn projects and models
Most of the C code is copied from Nihui, cause of the directory structure had to be adjusted, the original git was broken

https://github.com/nihui/realsr-ncnn-vulkan
https://github.com/nihui/srmd-ncnn-vulkan
https://github.com/nihui/waifu2x-ncnn-vulkan
https://github.com/nihui/realcugan-ncnn-vulkan
```

**Comment by ARTUROSING** [comment]
Or you can try adding the Real Esrgan + LDL model to the repository of this implementation, there is a code for converting to NCNN. Thank you.

**Comment by tumuyan** [comment]
> Or you can try adding the Real Esrgan + LDL model to the repository of this implementation, there is a code for converting to NCNN. Thank you.

As far as I know, the model needs to be convert and the pre-processing and inference code needs to be rewritten for ncnn. realsr and realesrgan could use same program cause of the authors are in same team.A-ESRGAN and LDL couldn‘t use it

**Comment by tumuyan** [comment]
I have try models in this site, most of them could be converted to ncnn models and run on realsr-ncnn
https://upscale.wiki/wiki/Model_Database

you could get the tool from cupscal  https://github.com/n00mkrad/cupscale/releases , in path CupscaleData\bin\pth2ncnn

**Comment by ARTUROSING** [comment]
Try to convert this model to NCNN and add. program. Link to google drive with the model. https://drive.google.com/file/d/12-EJmXqjoFCe_gFn9db8eLxBAo37tc8F/view?usp=drivesdk

**Comment by tumuyan** [comment]
> Try to convert this model to NCNN and add. program. Link to google drive with the model. https://drive.google.com/file/d/12-EJmXqjoFCe_gFn9db8eLxBAo37tc8F/view?usp=drivesdk

It is not a public file.  Actually you could try cupscale to convert it and do some test

**Comment by ARTUROSING** [comment]
Hello tumuyan.

Could you add realesr-general-x4v3.pth model, it should be fully compatible. When is the new update coming out?
Thank you, very much looking forward to your reply!
